In [49]:
import pandas as pd
df = pd.read_csv(r'C:\Users\onars\OneDrive\Desktop\Project UNO\shopping_behavior_updated (1).csv')

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   str
 15  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(11)
memory usage: 487.6 KB

In [51]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [52]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [53]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={"purchase_amount_(usd)": "purchase_amount"})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   str
 12  discount_applied        3900 non-null   str
 13  previous_purchases      3900 non-null   int64
 14  payment_method          3900 non-null   str
 15  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(11)
memory usage: 487.6 KB

In [54]:
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group'] =pd.qcut(df['age'], q=4, labels = labels)

In [55]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

In [56]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Annually' : 365,
    'Every 3 Months' :90
}
df['purchases_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [57]:
df[['purchases_frequency_days','frequency_of_purchases']].head(10)

   purchases_frequency_days frequency_of_purchases
0                      14.0            Fortnightly
1                      14.0            Fortnightly
2                       7.0                 Weekly
3                       7.0                 Weekly
4                     365.0               Annually
5                       7.0                 Weekly
6                      90.0              Quarterly
7                       7.0                 Weekly
8                     365.0               Annually
9                      90.0              Quarterly

In [58]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in .\.venv\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in .\.venv\Lib\site-packages (2.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [59]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "01022179191" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.